### ISSUE TITLE
Introducing character embedding in SNLI 

### ISSUE THREAD

**Issue by thak123** [imran3180/pytorch-nli#1]
How do I put character level embeddings for the text field

**Comment by imran3180** [comment]
I did not added support for character level embedding. But It can be added using [Nested Field](https://torchtext.readthedocs.io/en/latest/data.html#torchtext.data.NestedField). You can find examples of how to use Nested Field to generate character level embedding[ here.](https://github.com/pytorch/text/blob/master/test/data/test_field.py#L548)
