### ISSUE TITLE
Support for the TSV format dataset

### ISSUE THREAD

**Issue by chaochun** [imran3180/pytorch-nli#2]
Hi, does your code support the TSV format dataset? Or any suggestion to run your system for the TSV format datasets?

**Comment by imran3180** [comment]
Currently, it is reading from the JSON format dataset. But it can be modified very easily to read from TSV format. I am using [torchtext dataset splits method](https://torchtext.readthedocs.io/en/latest/datasets.html#torchtext.datasets.SNLI.splits) to prepare the [SNLI](https://github.com/imran3180/pytorch-nli/blob/master/datasets/snli.py#L17) and [MultiNLI](https://github.com/imran3180/pytorch-nli/blob/master/datasets/multinli.py#L17) datasets. 

By default splits methods reads from JSON files which are stored into .data folder. You can give your .tsv file name here and put your TSV file in .data folder. It should work right away. If you want to give own custom file path I would recommend you to use the tabular dataset from the torchtext and specify the path of TSV files.

**Comment by chaochun** [comment]
Thanks for your suggestions. :-)
